web.port=9900

db.host=172.31.21.29
db.port=13306
db.name=xxl_job_dev
db.user=dev
db.pwd=Dev2023@#!

mail.host=smtp.163.com
mail.port=465
mail.username=nexextablen@163.com
mail.from=no-reply
mail.pwd=IBRZCAMIFKXPJXQK

xxljob.token=xxl-job-access-token-gpthk-2023!
