web.port=9900

db.host=ex-prod.c7tokyfrpfd9.ap-east-1.rds.amazonaws.com
db.port=3306
db.name=xxl_job
db.user=
db.pwd=

mail.host=smtp.163.com
mail.port=465
mail.username=nexextablen@163.com
mail.from=no-reply
mail.pwd=IBRZCAMIFKXPJXQK

xxljob.token=xxl-job-access-token-gpthk-2023!Prod
